//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kzonlineEntities : DbContext
    {
        public kzonlineEntities()
            : base("name=kzonlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_AccountHead> tb_AccountHead { get; set; }
        public DbSet<tb_AccountsMaster> tb_AccountsMaster { get; set; }
        public DbSet<tb_Activity> tb_Activity { get; set; }
        public DbSet<tb_ActivityMaster> tb_ActivityMaster { get; set; }
        public DbSet<tb_ActivitySubMaster> tb_ActivitySubMaster { get; set; }
        public DbSet<tb_AdminActivity> tb_AdminActivity { get; set; }
        public DbSet<tb_ApplicationPage> tb_ApplicationPage { get; set; }
        public DbSet<tb_AvtarPictureMaster> tb_AvtarPictureMaster { get; set; }
        public DbSet<tb_Billing_Informatoin> tb_Billing_Informatoin { get; set; }
        public DbSet<tb_BulkEmailSystem> tb_BulkEmailSystem { get; set; }
        public DbSet<tb_BullshitWord> tb_BullshitWord { get; set; }
        public DbSet<tb_ButtonMaster> tb_ButtonMaster { get; set; }
        public DbSet<tb_CareerWithUs> tb_CareerWithUs { get; set; }
        public DbSet<tb_CategoryMaster> tb_CategoryMaster { get; set; }
        public DbSet<tb_CategoryTemplate> tb_CategoryTemplate { get; set; }
        public DbSet<tb_ClassMaster> tb_ClassMaster { get; set; }
        public DbSet<tb_Company> tb_Company { get; set; }
        public DbSet<tb_Contactus> tb_Contactus { get; set; }
        public DbSet<tb_Counselling> tb_Counselling { get; set; }
        public DbSet<tb_CounsellingFranchisee> tb_CounsellingFranchisee { get; set; }
        public DbSet<tb_CountryMaster> tb_CountryMaster { get; set; }
        public DbSet<tb_CountryMasterOld> tb_CountryMasterOld { get; set; }
        public DbSet<tb_DefaultPermission> tb_DefaultPermission { get; set; }
        public DbSet<tb_EmailAddressBook> tb_EmailAddressBook { get; set; }
        public DbSet<tb_emailsBAComp> tb_emailsBAComp { get; set; }
        public DbSet<tb_emailsDescription> tb_emailsDescription { get; set; }
        public DbSet<tb_EmailToFriend> tb_EmailToFriend { get; set; }
        public DbSet<tb_employeeMaster> tb_employeeMaster { get; set; }
        public DbSet<tb_EmployeeSalary> tb_EmployeeSalary { get; set; }
        public DbSet<tb_EnglishTestMaster> tb_EnglishTestMaster { get; set; }
        public DbSet<tb_ExamMaster> tb_ExamMaster { get; set; }
        public DbSet<tb_ExamResults> tb_ExamResults { get; set; }
        public DbSet<tb_FamilyUser> tb_FamilyUser { get; set; }
        public DbSet<tb_Feedback> tb_Feedback { get; set; }
        public DbSet<tb_FlashLibMaster> tb_FlashLibMaster { get; set; }
        public DbSet<tb_Formula> tb_Formula { get; set; }
        public DbSet<tb_HeaderDetail> tb_HeaderDetail { get; set; }
        public DbSet<tb_HeaderMaster> tb_HeaderMaster { get; set; }
        public DbSet<tb_Help> tb_Help { get; set; }
        public DbSet<tb_Keywords> tb_Keywords { get; set; }
        public DbSet<tb_LessionMaster> tb_LessionMaster { get; set; }
        public DbSet<tb_LessionMasterDetail> tb_LessionMasterDetail { get; set; }
        public DbSet<tb_LessionQuizMaster> tb_LessionQuizMaster { get; set; }
        public DbSet<tb_LessionQuizResults> tb_LessionQuizResults { get; set; }
        public DbSet<tb_LessonQuesType> tb_LessonQuesType { get; set; }
        public DbSet<tb_LessonTestDone> tb_LessonTestDone { get; set; }
        public DbSet<tb_MetatagMaster> tb_MetatagMaster { get; set; }
        public DbSet<tb_NotePadMaster> tb_NotePadMaster { get; set; }
        public DbSet<tb_OnlineTestMaster> tb_OnlineTestMaster { get; set; }
        public DbSet<tb_pageMaster> tb_pageMaster { get; set; }
        public DbSet<tb_PageTemplate> tb_PageTemplate { get; set; }
        public DbSet<tb_PageTemplateDetail> tb_PageTemplateDetail { get; set; }
        public DbSet<tb_PayPaPaymentHistory> tb_PayPaPaymentHistory { get; set; }
        public DbSet<tb_ProductClassMaster> tb_ProductClassMaster { get; set; }
        public DbSet<tb_ProductLinkedClass> tb_ProductLinkedClass { get; set; }
        public DbSet<tb_ProductMaster> tb_ProductMaster { get; set; }
        public DbSet<tb_QualificationMaster> tb_QualificationMaster { get; set; }
        public DbSet<tb_Question> tb_Question { get; set; }
        public DbSet<tb_QuesTypeMaster> tb_QuesTypeMaster { get; set; }
        public DbSet<tb_QuizDetail> tb_QuizDetail { get; set; }
        public DbSet<tb_QuizMaster> tb_QuizMaster { get; set; }
        public DbSet<tb_QuizResults> tb_QuizResults { get; set; }
        public DbSet<tb_QuizTestMaster> tb_QuizTestMaster { get; set; }
        public DbSet<tb_QuizTestMasterDetail> tb_QuizTestMasterDetail { get; set; }
        public DbSet<tb_realLogMaster> tb_realLogMaster { get; set; }
        public DbSet<tb_RegCategory> tb_RegCategory { get; set; }
        public DbSet<tb_ReportParameter> tb_ReportParameter { get; set; }
        public DbSet<tb_RequestQuote> tb_RequestQuote { get; set; }
        public DbSet<tb_ServiceMaster> tb_ServiceMaster { get; set; }
        public DbSet<tb_Solution> tb_Solution { get; set; }
        public DbSet<tb_StarInformation> tb_StarInformation { get; set; }
        public DbSet<tb_StateMaster> tb_StateMaster { get; set; }
        public DbSet<tb_SubCategoryMaster> tb_SubCategoryMaster { get; set; }
        public DbSet<tb_SubjectMaster> tb_SubjectMaster { get; set; }
        public DbSet<tb_SubProjectDetail> tb_SubProjectDetail { get; set; }
        public DbSet<tb_subscribe> tb_subscribe { get; set; }
        public DbSet<tb_Subscription> tb_Subscription { get; set; }
        public DbSet<tb_SubTitleMaster> tb_SubTitleMaster { get; set; }
        public DbSet<tb_TaskDetail> tb_TaskDetail { get; set; }
        public DbSet<tb_taskDetailDefault> tb_taskDetailDefault { get; set; }
        public DbSet<tb_TaskDetailStandard> tb_TaskDetailStandard { get; set; }
        public DbSet<tb_TaskMaster> tb_TaskMaster { get; set; }
        public DbSet<tb_TaskPermission> tb_TaskPermission { get; set; }
        public DbSet<tb_TeacherHelp> tb_TeacherHelp { get; set; }
        public DbSet<tb_TeacherPermission> tb_TeacherPermission { get; set; }
        public DbSet<tb_TeacherPermissionLesson> tb_TeacherPermissionLesson { get; set; }
        public DbSet<tb_ThemeContent> tb_ThemeContent { get; set; }
        public DbSet<tb_ThemeMaster> tb_ThemeMaster { get; set; }
        public DbSet<tb_UnitMaster> tb_UnitMaster { get; set; }
        public DbSet<tb_UploadTypeMaster> tb_UploadTypeMaster { get; set; }
        public DbSet<tb_UsefulTips> tb_UsefulTips { get; set; }
        public DbSet<tb_UserCategory> tb_UserCategory { get; set; }
        public DbSet<tb_UserLoginHistory> tb_UserLoginHistory { get; set; }
        public DbSet<tb_UserPageHistory> tb_UserPageHistory { get; set; }
        public DbSet<tb_UserUnitInformation> tb_UserUnitInformation { get; set; }
        public DbSet<tb_WebMasterInfo> tb_WebMasterInfo { get; set; }
        public DbSet<tb_HaveAQuestion> tb_HaveAQuestion { get; set; }
        public DbSet<tb_ModuleMaster> tb_ModuleMaster { get; set; }
        public DbSet<tb_UserMaster> tb_UserMaster { get; set; }
        public DbSet<tb_CityMaster> tb_CityMaster { get; set; }
        public DbSet<tb_ImagesUploaded> tb_ImagesUploaded { get; set; }
        public DbSet<tb_LessionMasterSlides> tb_LessionMasterSlides { get; set; }
    }
}
