//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BulkEmailSystem
    {
        public int AutoId { get; set; }
        public Nullable<System.DateTime> DateOfSent { get; set; }
        public string EmailDescription { get; set; }
        public string Ipaddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string BulkEmailSubject { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string DeleteStatus { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    }
}
