//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CountryMaster
    {
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryDescription { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<decimal> StatePer { get; set; }
        public Nullable<decimal> DistrictPer { get; set; }
        public Nullable<decimal> BAPer { get; set; }
    }
}
