//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CityMaster
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public string CityDescripton { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<decimal> BAPer { get; set; }
        public Nullable<decimal> State_Direct { get; set; }
        public Nullable<decimal> From_District { get; set; }
        public Nullable<decimal> BA_Per { get; set; }
        public Nullable<decimal> Dist_Fee { get; set; }
        public Nullable<int> BATarget { get; set; }
    }
}
