//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CounsellingFranchisee
    {
        public int ID { get; set; }
        public Nullable<int> ReferID { get; set; }
        public string EmailID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Cell { get; set; }
        public string EducationalQualification { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string MaritalStatus { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfExpire { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> NoOfDependents { get; set; }
        public string BestWayContact { get; set; }
        public string OtherCategory { get; set; }
        public string EmploymentStatus { get; set; }
        public Nullable<int> YearsofExperience { get; set; }
        public string ServiceInterested { get; set; }
        public string CountryInterestedFor { get; set; }
        public string FiancialStatus { get; set; }
        public string LanguageKnown { get; set; }
        public string LanguageProfeciency { get; set; }
        public string EnglishTest { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string TermsConditions { get; set; }
        public string AcceptNotAccept { get; set; }
        public string BusiProjectInterested { get; set; }
        public string BusiNameBusiness { get; set; }
        public string BusiTypeofBusiness { get; set; }
        public string BusiAddress { get; set; }
        public string BusiCity { get; set; }
        public string BusiState { get; set; }
        public string BusiCountry { get; set; }
        public string BusiSpace { get; set; }
        public string BusiCurrentBusinessOfficeArea { get; set; }
        public string BusiAnyOtherLandBuilForBusi { get; set; }
        public string BusiCurrentAssets { get; set; }
        public string BusiCurrentLiabilities { get; set; }
        public string BusiArrangedInvestment { get; set; }
        public string BusiSpecificProjectinformation { get; set; }
        public string BusiFax { get; set; }
        public string BusiPhone { get; set; }
        public Nullable<decimal> BusiPersonalInvestment { get; set; }
        public string SoftProjectDes { get; set; }
        public string SoftProjectName { get; set; }
        public string JobDescription { get; set; }
        public string JobTitle { get; set; }
        public string TrainingDescription { get; set; }
        public string TrainingInformation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string Status { get; set; }
        public string CounteryInterested { get; set; }
        public Nullable<int> Associateid { get; set; }
        public string DeleteStatus { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<int> MainCategoryId { get; set; }
        public Nullable<int> RegCategoryid { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public Nullable<int> countryid { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<int> countryid_inter { get; set; }
        public Nullable<System.DateTime> estimatedClosDate { get; set; }
        public string checkReplyIst { get; set; }
        public Nullable<int> FranCategory { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> StateID { get; set; }
    }
}
