//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ClassMaster
    {
        public int ClassesId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string ClassName { get; set; }
        public string ClasssDescription { get; set; }
        public string ClassImage { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<bool> Publish { get; set; }
    }
}
