//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmployeeSalary
    {
        public int Autoid { get; set; }
        public string EmpCode { get; set; }
        public Nullable<decimal> SalaryBasic { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> DayWorking { get; set; }
        public Nullable<decimal> DayWorked { get; set; }
        public Nullable<decimal> INCENTIVE { get; set; }
        public Nullable<decimal> CONVEYANCE { get; set; }
        public Nullable<decimal> OverTime { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<System.DateTime> AdvanceDate { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> Instalment { get; set; }
        public Nullable<System.DateTime> InstalmentDateStart { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Increment { get; set; }
        public string ESIYN { get; set; }
        public string PFYN { get; set; }
        public Nullable<decimal> FoodAllonce { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public Nullable<decimal> SalaryBasicCurrent { get; set; }
        public Nullable<decimal> HRACurrent { get; set; }
        public Nullable<decimal> empPF { get; set; }
        public Nullable<decimal> employerPF { get; set; }
        public Nullable<decimal> ESIAmount { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
