//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmailAddressBook
    {
        public int EmailId { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
        public string UserLastName { get; set; }
        public string CellNumber { get; set; }
        public string HomePhoneNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Website { get; set; }
        public string OfficePhoneNo { get; set; }
        public string OfficeFax { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DateofBrith { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateifAnniversary { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserType { get; set; }
        public string CompanyName { get; set; }
        public string Designation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ConfirmSubScription { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public string DeleteStatus { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    }
}
