//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_employeeMaster
    {
        public int AutoID { get; set; }
        public string EmpCode { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfbirth { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> DateofAppointment { get; set; }
        public Nullable<System.DateTime> LeftDate { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string BirthPlace { get; set; }
        public string BirthState { get; set; }
        public string BirthDistrict { get; set; }
        public string PfNo { get; set; }
        public string ESINo { get; set; }
        public string BonusType { get; set; }
        public string LeftYN { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> HraPercentage { get; set; }
        public string sex { get; set; }
        public string PolicyNumber { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Incentive { get; set; }
    }
}
