//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_FamilyUser
    {
        public int Userid { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string EmailId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string ContactNo { get; set; }
        public string UserAddress { get; set; }
        public string Schoolname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string IDProof { get; set; }
        public string DOBProof { get; set; }
        public string ProfilePicture { get; set; }
        public string ZipCode { get; set; }
        public string Street { get; set; }
        public string UnitHouseNo { get; set; }
        public string TownCity { get; set; }
        public string Ipaddress { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ClassId { get; set; }
    }
}
