//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Help
    {
        public int AutoId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> SlideId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string Ipaddress { get; set; }
    }
}
