//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LessionQuizMaster
    {
        public int AutoId { get; set; }
        public Nullable<int> LessionId { get; set; }
        public string QuizHeading { get; set; }
        public string QuizDesc { get; set; }
        public string Ans1 { get; set; }
        public string Ans2 { get; set; }
        public string Ans3 { get; set; }
        public string Ans4 { get; set; }
        public Nullable<int> ActualAns { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<int> QuesType { get; set; }
        public Nullable<bool> QuesBoolAns { get; set; }
        public string QuesCheckAns { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<bool> check1 { get; set; }
        public Nullable<bool> check2 { get; set; }
        public Nullable<bool> check3 { get; set; }
        public Nullable<bool> check4 { get; set; }
    }
}
