//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LessionMasterSlides
    {
        public int AutoId { get; set; }
        public Nullable<int> LessionId { get; set; }
        public string SlideDescription { get; set; }
        public string ImagePath { get; set; }
        public string ImageDescription { get; set; }
        public string Mp3Files { get; set; }
        public string VideoFiles { get; set; }
        public string GameFiles { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public Nullable<int> TotalView { get; set; }
        public Nullable<int> Downloads { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Ipaddress { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<int> SlideTypeId { get; set; }
        public Nullable<int> ThemeId { get; set; }
        public Nullable<int> UploadTypeId { get; set; }
        public string Description2 { get; set; }
        public Nullable<int> UploadTypeId1 { get; set; }
        public string FilePath { get; set; }
        public string FilePath1 { get; set; }
        public string GameFiles1 { get; set; }
        public string Mp3Files1 { get; set; }
        public string VideoFiles1 { get; set; }
        public string ImagePath1 { get; set; }
        public string HelpSlide { get; set; }
        public string RefSlide { get; set; }
        public string Quick { get; set; }
        public string UsefulTips { get; set; }
        public string Question { get; set; }
        public string Quiz { get; set; }
        public string FeedBack { get; set; }
        public string Solution { get; set; }
        public string Formula { get; set; }
        public Nullable<int> SlideId { get; set; }
        public string SpeechText { get; set; }
        public Nullable<int> UploadTypeId2 { get; set; }
        public Nullable<int> UploadTypeId3 { get; set; }
        public Nullable<int> UploadTypeId4 { get; set; }
        public string ImagePath2 { get; set; }
        public string ImagePath3 { get; set; }
        public string ImagePath4 { get; set; }
        public string Iframe1 { get; set; }
        public string Iframe2 { get; set; }
        public string Iframe3 { get; set; }
        public string Iframe4 { get; set; }
        public string iframe5 { get; set; }
    }
}
