//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LessionMasterDetail
    {
        public int AutoId { get; set; }
        public Nullable<int> LessionId { get; set; }
        public string LessionHeading { get; set; }
        public string LessionDesc { get; set; }
        public string imagePath { get; set; }
        public string VideoPath { get; set; }
        public Nullable<int> Userid { get; set; }
        public string Ipaddress { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> TotalView { get; set; }
        public Nullable<int> downloads { get; set; }
        public string LessionDesc1 { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> dispOrder { get; set; }
    }
}
