//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OnlineTestMaster
    {
        public int TestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TotalQuestion { get; set; }
        public Nullable<int> TotalCorrect { get; set; }
        public Nullable<int> TotalWrong { get; set; }
        public string Remarks { get; set; }
        public string Ipaddress { get; set; }
        public System.DateTime SystemDate { get; set; }
        public Nullable<int> CateId { get; set; }
        public Nullable<int> SubCateId { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> LessonID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<int> StarRating { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
