//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductClassMaster
    {
        public int AutoId { get; set; }
        public string ClassName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string ImageClass { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Duration { get; set; }
    }
}
