//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PayPaPaymentHistory
    {
        public int Autoid { get; set; }
        public string TokenNo { get; set; }
        public Nullable<decimal> Gross_ms { get; set; }
        public string protection_eligibility { get; set; }
        public string address_status { get; set; }
        public string payer_id { get; set; }
        public string tax { get; set; }
        public string address_street { get; set; }
        public string payment_date { get; set; }
        public string address_zip { get; set; }
        public string first_name { get; set; }
        public string mc_fee { get; set; }
        public string address_country_code { get; set; }
        public string address_name { get; set; }
        public string payer_status { get; set; }
        public string business { get; set; }
        public string address_country { get; set; }
        public string address_city { get; set; }
        public Nullable<int> quantity { get; set; }
        public string payer_email { get; set; }
        public string payment_type { get; set; }
        public string btn_id { get; set; }
        public string last_name { get; set; }
        public string address_state { get; set; }
        public string receiver_email { get; set; }
        public string payment_fee { get; set; }
        public string shipping_discount { get; set; }
        public string insurance_amount { get; set; }
        public string item_name { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string mc_currency { get; set; }
        public string item_number { get; set; }
        public string residence_country { get; set; }
        public string receipt_id { get; set; }
        public string shipping_method { get; set; }
        public string handling_amount { get; set; }
        public string transaction_subject { get; set; }
        public Nullable<decimal> payment_gross { get; set; }
        public string shipping { get; set; }
        public string ipn_track_id { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string DeleteStatus { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    }
}
