//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QuizMaster
    {
        public int AutoId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string QuizHeading { get; set; }
        public string QuizDesc { get; set; }
        public Nullable<bool> RandomOrder { get; set; }
        public Nullable<bool> ShowCorrectAns { get; set; }
        public Nullable<int> QuizPassingScore { get; set; }
        public Nullable<bool> ShowIntroPage { get; set; }
        public string IfPass { get; set; }
        public string IfFail { get; set; }
        public Nullable<bool> ShowReCap { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<int> SlideId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> UnitId { get; set; }
    }
}
