//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QuizTestMaster
    {
        public int AutoId { get; set; }
        public string TestHeading { get; set; }
        public string TestDesc { get; set; }
        public Nullable<bool> RandomOrder { get; set; }
        public Nullable<int> TestPassingScore { get; set; }
        public Nullable<bool> ShowIntroPage { get; set; }
        public string IfPass { get; set; }
        public string IfFail { get; set; }
        public Nullable<bool> ShowReCap { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string TestImage { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> totalQues { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<bool> isShow { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> PassingScore { get; set; }
        public Nullable<bool> Publish { get; set; }
    }
}
