//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_QuizDetail
    {
        public int AutoId { get; set; }
        public Nullable<int> RefId { get; set; }
        public Nullable<int> QuesTypeId { get; set; }
        public string Decription { get; set; }
        public string Ans1 { get; set; }
        public string Ans2 { get; set; }
        public string Ans3 { get; set; }
        public string Ans4 { get; set; }
        public string Ans5 { get; set; }
        public string Ans6 { get; set; }
        public string AllOfAbove { get; set; }
        public string NoneOfAbove { get; set; }
        public Nullable<bool> Check1 { get; set; }
        public Nullable<bool> Check2 { get; set; }
        public Nullable<bool> Check3 { get; set; }
        public Nullable<bool> Check4 { get; set; }
        public Nullable<bool> Check5 { get; set; }
        public Nullable<bool> Check6 { get; set; }
        public Nullable<bool> Check7 { get; set; }
        public Nullable<bool> Check8 { get; set; }
        public Nullable<int> ActualAns { get; set; }
        public Nullable<int> PointValue { get; set; }
        public Nullable<int> NoTries { get; set; }
        public string HelpQuiz { get; set; }
        public string Tutorial { get; set; }
        public string Solution { get; set; }
        public string Formulas { get; set; }
        public string Quick { get; set; }
        public string UsefulTips { get; set; }
        public string Question { get; set; }
        public string FeedBack { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<int> ActualAns1 { get; set; }
        public Nullable<bool> ShowInExam { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> SlideId { get; set; }
    }
}
