//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ReportParameter
    {
        public int AutoId { get; set; }
        public string ParaName { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
    }
}
