//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_StateMaster
    {
        public int StateID { get; set; }
        public string StateName { get; set; }
        public string StateDescription { get; set; }
        public int CountryID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<decimal> Country_Direct { get; set; }
        public Nullable<decimal> From_State { get; set; }
        public Nullable<decimal> From_District { get; set; }
        public Nullable<decimal> State_Fee { get; set; }
    }
}
