//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_StarInformation
    {
        public int AutoId { get; set; }
        public string StarName { get; set; }
        public Nullable<int> StarScore { get; set; }
        public string ImagePath { get; set; }
        public string Mp3Path { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
    }
}
