//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UnitMaster
    {
        public int UnitId { get; set; }
        public Nullable<int> ClassesId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string UnitName { get; set; }
        public string UnitDesc { get; set; }
        public string UnitImage { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string IntroductionPage { get; set; }
        public string IfPass { get; set; }
        public string IfFail { get; set; }
        public Nullable<bool> Publish { get; set; }
    }
}
