//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserMaster
    {
        public int UserId { get; set; }
        public string Picture { get; set; }
        public string AvtarName { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string SchoolName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string IDProof { get; set; }
        public string DOBProof { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string ConfirmPassword { get; set; }
        public string ProfileName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public string UnitHouseNo { get; set; }
        public string TownCity { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> ConfirmId { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<bool> Terms { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Ipaddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<System.DateTime> AgreementStartDate { get; set; }
        public Nullable<System.DateTime> AgreementEndDate { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string age { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<int> TeacherAssginedID { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> CityID { get; set; }
    }
}
