//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserUnitInformation
    {
        public int AutoId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> TotalLesson { get; set; }
        public Nullable<int> TotalTested { get; set; }
        public Nullable<bool> FinalTestStatus { get; set; }
        public Nullable<int> TotalQuestion { get; set; }
        public Nullable<int> TotalRight { get; set; }
        public Nullable<int> TotalWrong { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> TestRefId { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<bool> UnitStatus { get; set; }
        public Nullable<int> TryDone { get; set; }
    }
}
